
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCiviciFPointBase;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCiviciFPointExtended;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoChange;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoFidc;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoReplace;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoStory;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetData;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetInfo;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetTipoVia;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetValue;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetViaFCode;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetViaFCodeExtended;
import org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetVieFTopo;

/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Toponomastica4.5PortType", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
        com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
        org.datacontract.schemas._2004._07.wcftopo.ObjectFactory.class,
        org.tempuri.ObjectFactory.class
})
public interface Toponomastica45PortType {

    /**
     * 
     * @param pToken
     * @param pToponomy
     * @param pType
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetVieFTopo
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetVieFTopo")
    @WebResult(name = "sitGetVieFTopoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetVieFTopo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetVieFTopo")
    @ResponseWrapper(localName = "sitGetVieFTopoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetVieFTopoResponse")
    public TopoServiceTypeGetVieFTopo sitGetVieFTopo(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pToponomy", targetNamespace = "http://tempuri.org/") String pToponomy,
            @WebParam(name = "pType", targetNamespace = "http://tempuri.org/") String pType);

    /**
     * 
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetInfo
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetInfo")
    @WebResult(name = "sitGetInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetInfo")
    @ResponseWrapper(localName = "sitGetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetInfoResponse")
    public TopoServiceTypeGetInfo sitGetInfo(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken);

    /**
     * 
     * @param pCode
     * @param pCoordinateX
     * @param pCoordinateY
     * @param pReference
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetValue
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetValueFPoint")
    @WebResult(name = "sitGetValueFPointResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetValueFPoint", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFPoint")
    @ResponseWrapper(localName = "sitGetValueFPointResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFPointResponse")
    public TopoServiceTypeGetValue sitGetValueFPoint(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pCode", targetNamespace = "http://tempuri.org/") String pCode,
            @WebParam(name = "pCoordinateX", targetNamespace = "http://tempuri.org/") Double pCoordinateX,
            @WebParam(name = "pCoordinateY", targetNamespace = "http://tempuri.org/") Double pCoordinateY,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference);

    /**
     * 
     * @param pToken
     * @param pType
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetTipoVia
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetTipoVia")
    @WebResult(name = "sitGetTipoViaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetTipoVia", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetTipoVia")
    @ResponseWrapper(localName = "sitGetTipoViaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetTipoViaResponse")
    public TopoServiceTypeGetTipoVia sitGetTipoVia(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pType", targetNamespace = "http://tempuri.org/") String pType);

    /**
     * 
     * @param pCode
     * @param pPolygonJson
     * @param pReference
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetValue
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetValueFPolygon")
    @WebResult(name = "sitGetValueFPolygonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetValueFPolygon", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFPolygon")
    @ResponseWrapper(localName = "sitGetValueFPolygonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFPolygonResponse")
    public TopoServiceTypeGetValue sitGetValueFPolygon(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pCode", targetNamespace = "http://tempuri.org/") String pCode,
            @WebParam(name = "pPolygonJson", targetNamespace = "http://tempuri.org/") String pPolygonJson,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference);

    /**
     * 
     * @param pIDC
     * @param pReference
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoFidc
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCivicoFidc")
    @WebResult(name = "sitGetCivicoFidcResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCivicoFidc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoFidc")
    @ResponseWrapper(localName = "sitGetCivicoFidcResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoFidcResponse")
    public TopoServiceTypeGetCivicoFidc sitGetCivicoFidc(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pIDC", targetNamespace = "http://tempuri.org/") Integer pIDC,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference);

    /**
     * 
     * @param pCoordinateX
     * @param pCoordinateY
     * @param pDistance
     * @param pNumber
     * @param pReference
     * @param pState
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCiviciFPointBase
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCiviciFPointBase")
    @WebResult(name = "sitGetCiviciFPointBaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCiviciFPointBase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCiviciFPointBase")
    @ResponseWrapper(localName = "sitGetCiviciFPointBaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCiviciFPointBaseResponse")
    public TopoServiceTypeGetCiviciFPointBase sitGetCiviciFPointBase(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pCoordinateX", targetNamespace = "http://tempuri.org/") Double pCoordinateX,
            @WebParam(name = "pCoordinateY", targetNamespace = "http://tempuri.org/") Double pCoordinateY,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference,
            @WebParam(name = "pState", targetNamespace = "http://tempuri.org/") Integer pState,
            @WebParam(name = "pNumber", targetNamespace = "http://tempuri.org/") Integer pNumber,
            @WebParam(name = "pDistance", targetNamespace = "http://tempuri.org/") Double pDistance);

    /**
     * 
     * @param pCivic
     * @param pReference
     * @param pState
     * @param pStreetCode
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetViaFCode
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetViaFCode")
    @WebResult(name = "sitGetViaFCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetViaFCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetViaFCode")
    @ResponseWrapper(localName = "sitGetViaFCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetViaFCodeResponse")
    public TopoServiceTypeGetViaFCode sitGetViaFCode(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pStreetCode", targetNamespace = "http://tempuri.org/") Integer pStreetCode,
            @WebParam(name = "pCivic", targetNamespace = "http://tempuri.org/") String pCivic,
            @WebParam(name = "pState", targetNamespace = "http://tempuri.org/") Integer pState,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference);

    /**
     * 
     * @param pData1
     * @param pData2
     * @param pIDC
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoStory
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCivicoStory")
    @WebResult(name = "sitGetCivicoStoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCivicoStory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoStory")
    @ResponseWrapper(localName = "sitGetCivicoStoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoStoryResponse")
    public TopoServiceTypeGetCivicoStory sitGetCivicoStory(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pIDC", targetNamespace = "http://tempuri.org/") Integer pIDC,
            @WebParam(name = "pData1", targetNamespace = "http://tempuri.org/") String pData1,
            @WebParam(name = "pData2", targetNamespace = "http://tempuri.org/") String pData2);

    /**
     * 
     * @param pCivic
     * @param pReference
     * @param pState
     * @param pStreetCode
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetViaFCodeExtended
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetViaFCodeExtended")
    @WebResult(name = "sitGetViaFCodeExtendedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetViaFCodeExtended", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetViaFCodeExtended")
    @ResponseWrapper(localName = "sitGetViaFCodeExtendedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetViaFCodeExtendedResponse")
    public TopoServiceTypeGetViaFCodeExtended sitGetViaFCodeExtended(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pStreetCode", targetNamespace = "http://tempuri.org/") Integer pStreetCode,
            @WebParam(name = "pCivic", targetNamespace = "http://tempuri.org/") String pCivic,
            @WebParam(name = "pState", targetNamespace = "http://tempuri.org/") Integer pState,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference);

    /**
     * 
     * @param pIDC
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoReplace
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCivicoReplace")
    @WebResult(name = "sitGetCivicoReplaceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCivicoReplace", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoReplace")
    @ResponseWrapper(localName = "sitGetCivicoReplaceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoReplaceResponse")
    public TopoServiceTypeGetCivicoReplace sitGetCivicoReplace(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pIDC", targetNamespace = "http://tempuri.org/") Integer pIDC);

    /**
     * 
     * @param pData1
     * @param pData2
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCivicoChange
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCivicoChange")
    @WebResult(name = "sitGetCivicoChangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCivicoChange", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoChange")
    @ResponseWrapper(localName = "sitGetCivicoChangeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCivicoChangeResponse")
    public TopoServiceTypeGetCivicoChange sitGetCivicoChange(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pData1", targetNamespace = "http://tempuri.org/") String pData1,
            @WebParam(name = "pData2", targetNamespace = "http://tempuri.org/") String pData2);

    /**
     * 
     * @param pCoordinateX
     * @param pCoordinateY
     * @param pDistance
     * @param pNumber
     * @param pReference
     * @param pState
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetCiviciFPointExtended
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetCiviciFPointExtended")
    @WebResult(name = "sitGetCiviciFPointExtendedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetCiviciFPointExtended", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCiviciFPointExtended")
    @ResponseWrapper(localName = "sitGetCiviciFPointExtendedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetCiviciFPointExtendedResponse")
    public TopoServiceTypeGetCiviciFPointExtended sitGetCiviciFPointExtended(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pCoordinateX", targetNamespace = "http://tempuri.org/") Double pCoordinateX,
            @WebParam(name = "pCoordinateY", targetNamespace = "http://tempuri.org/") Double pCoordinateY,
            @WebParam(name = "pReference", targetNamespace = "http://tempuri.org/") Integer pReference,
            @WebParam(name = "pState", targetNamespace = "http://tempuri.org/") Integer pState,
            @WebParam(name = "pNumber", targetNamespace = "http://tempuri.org/") Integer pNumber,
            @WebParam(name = "pDistance", targetNamespace = "http://tempuri.org/") Double pDistance);

    /**
     * 
     * @param pCode
     * @param pIDC
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetValue
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetValueFidc")
    @WebResult(name = "sitGetValueFidcResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetValueFidc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFidc")
    @ResponseWrapper(localName = "sitGetValueFidcResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetValueFidcResponse")
    public TopoServiceTypeGetValue sitGetValueFidc(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pCode", targetNamespace = "http://tempuri.org/") String pCode,
            @WebParam(name = "pIDC", targetNamespace = "http://tempuri.org/") Integer pIDC);

    /**
     * 
     * @param pRiferimento
     * @param pToken
     * @return
     *         returns
     *         org.datacontract.schemas._2004._07.wcftopo.TopoServiceTypeGetData
     */
    @WebMethod(action = "http://tempuri.org/ITopoService/sitGetData")
    @WebResult(name = "sitGetDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sitGetData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetData")
    @ResponseWrapper(localName = "sitGetDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SitGetDataResponse")
    public TopoServiceTypeGetData sitGetData(
            @WebParam(name = "pToken", targetNamespace = "http://tempuri.org/") String pToken,
            @WebParam(name = "pRiferimento", targetNamespace = "http://tempuri.org/") String pRiferimento);

}
